// T6 smoke test: prove the exported weights.json produces the same
// predictions in JavaScript (the extension's actual tf.min.js bundle +
// the same model-building code as content.js) as the Keras model did.
//
// Run:  node tests/smoke_model.cjs
// Fixture (inputs + expected outputs) is generated by training/export_weights.py.
const path = require("path");

const tf = require(path.join(__dirname, "..", "extension", "lib", "tf.min.js"));
const spec = require(path.join(__dirname, "..", "extension", "model", "weights.json"));
const fixture = require(path.join(__dirname, "fixtures", "model_io.json"));

// Mirror of the model-building code in extension/content.js
const model = tf.sequential();
spec.layers.forEach((layer, i) => {
  model.add(tf.layers.dense({
    units: layer.units,
    activation: layer.activation,
    inputShape: i === 0 ? [spec.inputSize] : undefined,
  }));
});
model.setWeights(
  spec.layers.flatMap(l => [tf.tensor2d(l.kernel), tf.tensor1d(l.bias)])
);

const actual = model.predict(tf.tensor2d(fixture.inputs)).arraySync();

let maxDiff = 0;
for (let r = 0; r < fixture.expected.length; r++) {
  for (let c = 0; c < fixture.expected[r].length; c++) {
    maxDiff = Math.max(maxDiff, Math.abs(actual[r][c] - fixture.expected[r][c]));
  }
}

if (maxDiff > 1e-4) {
  console.error(`FAIL: JS predictions diverge from Keras (max diff ${maxDiff})`);
  process.exit(1);
}
console.log(`PASS: JS model matches Keras on ${fixture.inputs.length} samples ` +
            `(max diff ${maxDiff.toExponential(2)}, ${spec.labels.length} classes)`);
